export const MOCK_RESEARCH_BRIEF = `
# Research Brief: Enterprise AI Opportunities

**Generated by Agentic 10x Protocol**

## 1. Strategic Gaps
*   **Customer Service Automation:** Your backlog focuses on manual process improvements, but competitors are deploying GenAI chatbots for Tier 1 support.
*   **Predictive Maintenance:** No initiatives found for IoT data leverage, despite your heavy asset base.
*   **Dynamic Pricing:** Market leaders are using ML for real-time pricing; your backlog only lists static pricing rule updates.

## 2. Competitor Recon
*   "How is **Competitor X** utilizing Generative AI for customer onboarding?"
*   "What are the emerging regulatory risks for **Industry Y** in 2025?"

## 3. Risk Warning
> [!WARNING]
> **Legacy Infrastructure:** Your reliance on on-premise Oracle databases may bottle-neck the proposed "Real-Time Dashboard" initiatives.
`;

export const MOCK_IDEA_CARDS = [
    {
        id: 'card-1',
        title: 'GenAI Customer Support Bot',
        description: 'Implement a RAG-based chatbot to handle 80% of Tier 1 inquiries, reducing support costs.',
        tier: 'STRATEGIC_BET', // Tier 1 (Gold)
        source: 'MARKET_SIGNAL',
        status: 'ACTIVE',
        strategicCluster: 'Customer Experience',
        xPosition: 100,
        yPosition: 80,
        rotation: -1.2
    },
    {
        id: 'card-2',
        title: 'Migrate to Cloud ERP',
        description: 'Move core ledgers to AWS to enable real-time analytics.',
        tier: 'TABLE_STAKES', // Tier 2 (Blue)
        source: 'CLIENT_BACKLOG',
        status: 'ACTIVE',
        strategicCluster: 'Operational Efficiency',
        xPosition: 450,
        yPosition: 120,
        rotation: 0.8
    },
    {
        id: 'card-3',
        title: 'Automate Invoice Processing',
        description: 'Use OCR to auto-ingest PDF invoices from vendors.',
        tier: 'AGENTIC_AUTO', // Tier 3 (Grey)
        source: 'WORKSHOP_GENERATED',
        status: 'ACTIVE',
        strategicCluster: 'Logistics Optimization',
        xPosition: 800,
        yPosition: 60,
        rotation: -0.5
    },
    {
        id: 'card-4',
        title: 'Real-Time Fleet Tracking',
        description: 'IoT sensors on all delivery trucks to optimize routing.',
        tier: 'STRATEGIC_BET',
        source: 'CLIENT_BACKLOG',
        status: 'ACTIVE',
        strategicCluster: 'Logistics Optimization',
        xPosition: 200,
        yPosition: 350,
        rotation: 1.5
    },
    {
        id: 'card-5',
        title: 'Employee Self-Service Portal',
        description: 'Update the HR portal for leave requests.',
        tier: 'TABLE_STAKES',
        source: 'CLIENT_BACKLOG',
        status: 'ACTIVE',
        strategicCluster: 'Operational Efficiency',
        xPosition: 600,
        yPosition: 380,
        rotation: -0.3
    }
];


export const MOCK_BLIND_SPOTS = [
    { name: "AI Customer Service", status: "CRITICAL", evidence: "Market Signal: Competitor X launched 'GenAI Help' in Q3 2024, reducing tickets by 40%." },
    { name: "Predictive Analytics", status: "CRITICAL", evidence: "Trend Report: 80% of logistics firms now use IoT for predictive maintenance." },
    { name: "Cloud Native Ops", status: "ALIGNED", evidence: "Internal: You have already migrated 60% of workloads to AWS." }
];

export const MOCK_CLUSTERS = [
    { name: "Customer Experience", count: 12, horizon: "GROWTH", strategy: "Post26 CX Renovation" },
    { name: "Logistics Optimization", count: 8, horizon: "OPS EFFICIENCY", strategy: "Supply Chain 2.0" },
    { name: "Risk Management", count: 3, horizon: "STRATEGY", strategy: "Governance Framework" }
];

export const MOCK_FEASIBILITY = [
    { name: "Real-Time Fleet Tracking", status: "READY", evidence: "Tech Stack: AWS IoT Core is active." },
    { name: "GenAI Customer Support", status: "RISKY", evidence: "Tech Stack: No Vector DB found in architecture." },
    { name: "Cloud ERP Migration", status: "BLOCKED", evidence: "Tech Stack: Legacy Oracle on-premise is a hard dependency." },
    { name: "Automate Invoice Processing", status: "READY", evidence: "Tech Stack: Azure AI Document Intelligence is available." },
    { name: "Employee Portal", status: "READY", evidence: "Tech Stack: SharePoint Online is configured." }
];
